/**
 * Source metadata payload (as provided).
 * Keep this as the canonical “verbatim” snapshot so we never lose fields.
 */

export const applyUniNowCourseExplorerSource = {
  wizard: {
    name: 'ApplyUniNow Course Explorer',
    url: 'https://applyuninow.com/explore',
    totalSteps: 10,
    progressIndicator: 'vertical-timeline-dots',
    routes: {
      HOME: '/',
      COUNTRY: '/country',
      STUDY_LEVEL: '/study-level',
      INTAKE: '/intake',
      INDUSTRY: '/industry',
      STUDY_AREA: '/study-area',
      FORMAT: '/format',
      ACADEMICS: '/academics',
      CONTACT: '/contact',
      THANK_YOU: '/thank-you',
    },
    stepOrder: [
      '/',
      '/country',
      '/study-level',
      '/intake',
      '/industry',
      '/study-area',
      '/format',
      '/academics',
      '/contact',
      '/thank-you',
    ],
    stepLabels: {
      '/': 'Preferences',
      '/country': 'Country',
      '/study-level': 'Study Level',
      '/intake': 'Intake',
      '/industry': 'Industry',
      '/study-area': 'Study Area',
      '/format': 'Format',
      '/academics': 'Academics',
      '/contact': 'Contact',
      '/thank-you': 'Complete',
    },
    navigationFlow: {
      currentStepDerivedFrom: 'URL pathname index in stepOrder',
      progressPercentFormula: 'round((currentStep / (totalSteps - 1)) * 100)',
      goToNextRule:
        'navigate to stepOrder[currentStep+1] only if canProceedFromStep(currentStep) is true',
      goToPreviousRule: 'navigate to stepOrder[currentStep-1] when currentStep > 0',
      goHomeRule: "set step 0 and navigate to '/'",
    },
    navigation: {
      backButton: { enabled: true, icon: '<<<', position: 'top-left' },
      nextButton: { enabled: true, icon: '>>>', position: 'top-right' },
      progressBar: {
        type: 'gradient-bar',
        position: 'bottom',
        colors: ['#FFD700', '#FF6B6B', '#4ECDC4'],
      },
    },
    validationRulesByStepIndex: {
      '0': { route: '/', required: [], note: 'Home/tags optional' },
      '1': { route: '/country', required: ['country'] },
      '2': { route: '/study-level', required: ['studyLevel', 'degreeType'] },
      '3': { route: '/intake', required: ['intake', 'intakeYear', 'studyDuration'] },
      '4': { route: '/industry', required: ['industry'] },
      '5': { route: '/study-area', required: ['studyArea'] },
      '6': { route: '/format', required: ['studyFormat'] },
      '7': {
        route: '/academics',
        required: [
          'academics.secondary.year',
          'academics.secondary.grade',
          'academics.higherSecondary.year',
          'academics.higherSecondary.grade',
        ],
        note: 'medium fields are not required by canProceedFromStep',
      },
      '8': {
        route: '/contact',
        required: [
          'contact.firstName',
          'contact.lastName',
          'contact.phone',
          'contact.email',
          'contact.termsConsent',
        ],
        note: 'emailConsent is optional',
      },
      '9': { route: '/thank-you', required: [], note: 'Final confirmation screen' },
    },
  },
  steps: [
    {
      index: 0,
      stepId: 'preferences',
      route: '/',
      stepLabel: 'Preferences',
      component: 'MobileHomePage',
      title: 'Four Services + One Mission: Empowering global talent.',
      inputType: 'multi-select-tags',
      required: false,
      autoAdvance: false,
      storeWrites: ['selectedTags (toggleTag)'],
      primaryCta: { label: 'Next', action: 'goToNext()' },
      field: { name: 'selectedTags', type: 'array' },
      options: [
        { value: 'quick-offer', label: 'Quick Offer' },
        { value: 'course-internships', label: 'Course with Internships' },
        { value: 'high-acceptance', label: 'High Offer Acceptance-Rate' },
        { value: 'affordable-university', label: 'Affordable University' },
        { value: 'guaranteed-scholarship', label: 'Guaranteed Scholarship' },
        { value: 'trending-courses', label: 'Trending Courses' },
        { value: 'high-ranking', label: 'High Ranking Universities' },
        { value: 'outstanding-facilities', label: 'Outstanding Facilities' },
        { value: 'english-waiver', label: 'English Test Waiver' },
        { value: 'low-deposit', label: 'Low Tuition Deposit' },
        { value: 'backlog-acceptance', label: 'Backlog Acceptance' },
        { value: 'moi-acceptable', label: 'MOI Acceptable' },
        { value: 'professional-accreditations', label: 'Professional Accreditations' },
        { value: 'culture-social', label: 'Culture and Social Experience' },
        { value: 'affordable-living', label: 'Affordable Living' },
        { value: 'career-upskilling', label: 'Career Upskilling' },
        { value: 'quick-loans', label: 'Quick Education Loans' },
        { value: 'accommodation', label: 'Accommodation' },
        { value: 'part-time-jobs', label: 'Part Time Jobs' },
        { value: 'pre-departure', label: 'Pre-Departure' },
        { value: 'arrival-pickup', label: 'Destination - Arrival pickup' },
        { value: 'arrival-registrations', label: 'On - Arrival registrations' },
        { value: 'internship-subject', label: 'Internship (in-line to Subject area)' },
        { value: 'part-time-academics', label: 'Part-time jobs (in-line to academics / work experience)' },
      ],
      pageMetadata: {
        header: { logoSrc: '/assets/AUN Logo.svg', profileIcon: 'inline svg', menuIcon: 'inline svg' },
        tagline: {
          subtitle: 'Four Services + One Mission:',
          title: 'Empowering global talent.',
          highlights: ['Not just study options but', 'Experience the future-ready-courses.'],
        },
        stats: [
          { value: '12,000+', label: 'Students Helped', iconPath: '/assets/icons/stats/Students Helped icon.svg' },
          { value: '3,00,000+', label: 'Study Options', iconPath: '/assets/icons/stats/Study Options Icon.svg' },
          { value: '2,180', label: 'Global Universities', iconPath: '/assets/icons/stats/Global Universities icon.svg' },
          { value: '100%', label: 'Transparent Process', iconPath: '/assets/icons/stats/Transparent Process icon.svg' },
          { value: '500+', label: 'Global Events', iconPath: '/assets/icons/stats/Global Events icon.svg' },
          { value: '1,200+', label: 'Virtual sessions', iconPath: '/assets/icons/stats/Virtual sessions icon.svg' },
          { value: '100%', label: 'Student Satisfaction', iconPath: '/assets/icons/stats/Student satisfaction icon.svg' },
          { value: '20+', label: 'Study Destinations', iconPath: '/assets/icons/stats/Study destination Icon.svg' },
          { value: '12+', label: "Year's Experience", iconPath: '/assets/icons/stats/Years Experience icon.svg' },
        ],
        footer: {
          primaryLinks: ['About Us', 'EXPLORE', 'AI Student Advisor'],
          secondaryLinks: ['T&C', 'Privacy Policy', 'Refund Policy', 'Anti-Fraud Policy', 'Grievance'],
          contact: {
            title: 'Quick Question?',
            phones: ['+44 773 45 66688 UK', '+91 970 45 66688 IN'],
            email: 'support@applyuninow.com',
            copyright: 'Crafted by AUN Tech Consulting Pvt. Ltd.',
          },
        },
      },
    },
    {
      index: 1,
      stepId: 'country-selection',
      route: '/country',
      stepLabel: 'Country',
      component: 'CountrySelection',
      title: 'Choose Your Study Destination',
      inputType: 'single-select-grid',
      required: true,
      autoAdvance: true,
      storeWrites: ['country (setCountry)'],
      specialBehavior: [
        "On mount: setCountry('') (resets selection when entering page)",
        'On selecting a country: navigates directly to /study-level',
      ],
      field: { name: 'country', type: 'string' },
      options: [
        { value: 'australia', label: 'Australia', code: 'AU', flagUrl: '/assets/icons/flags/Australia.svg' },
        { value: 'canada', label: 'Canada', code: 'CA', flagUrl: '/assets/icons/flags/Canada.svg' },
        { value: 'uk', label: 'UK', code: 'GB', flagUrl: '/assets/icons/flags/UK.svg' },
        { value: 'usa', label: 'USA', code: 'US', flagUrl: '/assets/icons/flags/USA.svg' },
        { value: 'ireland', label: 'Ireland', code: 'IE', flagUrl: '/assets/icons/flags/Ireland.svg' },
        { value: 'germany', label: 'Germany', code: 'DE', flagUrl: '/assets/icons/flags/Germany.svg' },
        { value: 'switzerland', label: 'Switzerland', code: 'CH', flagUrl: '/assets/icons/flags/Switzerland.svg' },
        { value: 'sweden', label: 'Sweden', code: 'SE', flagUrl: '/assets/icons/flags/Sweden.svg' },
        { value: 'netherlands', label: 'Netherlands', code: 'NL', flagUrl: '/assets/icons/flags/Netherlands.svg' },
        { value: 'new-zealand', label: 'New Zealand', code: 'NZ', flagUrl: '/assets/icons/flags/NewZealand.svg' },
        { value: 'cyprus', label: 'Cyprus', code: 'CY', flagUrl: '/assets/icons/flags/Cyprus.svg' },
        { value: 'denmark', label: 'Denmark', code: 'DK', flagUrl: '/assets/icons/flags/Denmark.svg' },
        { value: 'france', label: 'France', code: 'FR', flagUrl: '/assets/icons/flags/France.svg' },
        { value: 'italy', label: 'Italy', code: 'IT', flagUrl: '/assets/icons/flags/Italy.svg' },
        { value: 'finland', label: 'Finland', code: 'FI', flagUrl: '/assets/icons/flags/Finland.svg' },
        { value: 'latvia', label: 'Latvia', code: 'LV', flagUrl: '/assets/icons/flags/Latvia.svg' },
        { value: 'malta', label: 'Malta', code: 'MT', flagUrl: '/assets/icons/flags/Malta.svg' },
        { value: 'norway', label: 'Norway', code: 'NO', flagUrl: '/assets/icons/flags/Norway.svg' },
        { value: 'poland', label: 'Poland', code: 'PL', flagUrl: '/assets/icons/flags/Poland.svg' },
        { value: 'singapore', label: 'Singapore', code: 'SG', flagUrl: '/assets/icons/flags/Singapore.svg' },
        { value: 'spain', label: 'Spain', code: 'ES', flagUrl: '/assets/icons/flags/Spain.svg' },
      ],
      nextButtonEnabledWhen: 'country is truthy (canProceed)',
    },
    {
      index: 2,
      stepId: 'study-level-selection',
      route: '/study-level',
      stepLabel: 'Study Level',
      component: 'StudyAreaSelection',
      title: 'Choose the most applicable Study Level that you would like to pursue ongoing',
      required: true,
      autoAdvance: false,
      storeWrites: ['studyLevel (setStudyLevel)', 'degreeType (setDegreeType)'],
      sections: [
        {
          sectionId: 'study-level',
          title: 'Study Level',
          inputType: 'single-select-tabs',
          field: { name: 'studyLevel', type: 'string' },
          options: [
            { id: 'summer', value: 'summer-programs', label: 'Summer Programs' },
            { id: 'diploma', value: 'diploma', label: 'Diploma' },
            { id: 'undergrad', value: 'under-graduation', label: 'Under Graduation' },
            { id: 'ug-integrated', value: 'ug-integrated', label: 'UG - Integrated' },
            { id: 'pre-masters', value: 'pre-masters', label: 'Pre Masters' },
            { id: 'postgrad', value: 'post-graduation', label: 'Post Graduation', default: true },
            { id: 'phd', value: 'phd', label: 'PhD (Doctor of Philosophy)' },
            { id: 'dba', value: 'dba', label: 'DBA (Doctorate of Business Administration)', multiline: true },
          ],
        },
        {
          sectionId: 'degree-type',
          title: 'Choose the applicable Degree type would you like to study overseas',
          inputType: 'single-select-chips',
          dependsOn: 'studyLevel',
          field: { name: 'degreeType', type: 'string' },
          conditionalOptions: {
            'post-graduation': [
              { id: 'msc', value: 'msc', label: 'MSc - Master of Science' },
              { id: 'mphil', value: 'mphil', label: 'M.Ph - Master of Philosophy' },
              { id: 'mba', value: 'mba', label: 'MBA - Masters of Business Administration' },
              { id: 'phd', value: 'phd', label: 'PhD - Doctor of Philosophy' },
              { id: 'doctorate', value: 'doctorate', label: 'Doctorate - Academics General' },
              { id: 'ma', value: 'ma', label: 'MA - Master of Arts' },
              { id: 'pgcert', value: 'pgcert', label: 'Postgraduate certificate' },
              { id: 'grad-diploma', value: 'grad-diploma', label: 'Graduate diploma' },
              { id: 'mres', value: 'mres', label: 'M.Res - Master of Research' },
              { id: 'med', value: 'med', label: 'M.Ed - Master of Education' },
              { id: 'llm', value: 'llm', label: 'LLM - Master of Laws' },
              { id: 'march', value: 'march', label: 'M.Arch - Master of Architecture' },
              { id: 'pgce', value: 'pgce', label: 'Postgraduate Certificate in Education' },
              { id: 'meng', value: 'meng', label: 'MEng - Master of Engineering' },
              { id: 'mem', value: 'mem', label: 'MEM - Masters of Engineering Management' },
              { id: 'mfa', value: 'mfa', label: 'MFA - Master of Fine Arts' },
              { id: 'msw', value: 'msw', label: 'MSW - Master of Social Work' },
              { id: 'master-business', value: 'master-business', label: 'Master of Business' },
              { id: 'md', value: 'md', label: 'M.D. - Doctor of Medicine' },
              { id: 'mfin', value: 'mfin', label: 'M.Fin/MiF/MFiN - Master of Finance' },
            ],
            'under-graduation': [
              { id: 'bsc', value: 'bsc', label: 'BSC - Bachelor of Science' },
              { id: 'ba', value: 'ba', label: 'BA - Bachelor of Arts' },
              { id: 'llb', value: 'llb', label: 'LLB - Bachelor of Laws' },
              { id: 'be', value: 'be', label: 'BE - Bachelor of Engineering' },
              { id: 'bba', value: 'bba', label: 'BBA - Bachelor of Business Administration' },
              { id: 'associate', value: 'associate', label: 'Associate Degree' },
              { id: 'academy-profession', value: 'academy-profession', label: 'Academy Profession' },
              { id: 'advanced-diploma', value: 'advanced-diploma', label: 'Advanced Diploma' },
              { id: 'joint-programs', value: 'joint-programs', label: 'Joint Programs' },
            ],
            phd: [
              { id: 'dba', value: 'dba', label: 'DBA (Doctorate of Business Administration)' },
              { id: 'phd', value: 'phd', label: 'PhD (Doctor of Philosophy)' },
            ],
            dba: [
              { id: 'dba', value: 'dba', label: 'DBA (Doctorate of Business Administration)' },
              { id: 'phd', value: 'phd', label: 'PhD (Doctor of Philosophy)' },
            ],
          },
        },
      ],
      nextButtonEnabledWhen: 'studyLevel and degreeType are truthy (canProceed)',
    },
    {
      index: 3,
      stepId: 'intake-selection',
      route: '/intake',
      stepLabel: 'Intake',
      component: 'IntakeYearSelection',
      title: "Choose the best suitable Intake and year that you're planning to join the University.",
      required: true,
      autoAdvance: false,
      storeWrites: ['intake (setIntake)', 'intakeYear (setIntakeYear)', 'studyDuration (setStudyDuration)'],
      fields: [
        {
          name: 'intake',
          label: 'Intake',
          type: 'string',
          inputType: 'dropdown',
          required: true,
          options: [
            { id: 'january', value: 'january', label: 'January' },
            { id: 'february', value: 'february', label: 'February' },
            { id: 'march', value: 'march', label: 'March' },
            { id: 'april', value: 'april', label: 'April' },
            { id: 'may', value: 'may', label: 'May' },
            { id: 'june', value: 'june', label: 'June' },
            { id: 'july', value: 'july', label: 'July' },
            { id: 'august', value: 'august', label: 'August' },
            { id: 'september', value: 'september', label: 'September' },
            { id: 'october', value: 'october', label: 'October' },
            { id: 'november', value: 'november', label: 'November' },
            { id: 'december', value: 'december', label: 'December' },
          ],
          seasonalMapping: [
            { id: 'spring', value: 'spring', label: 'Spring', months: ['march', 'april', 'may'] },
            { id: 'summer', value: 'summer', label: 'Summer', months: ['june', 'july', 'august'] },
            { id: 'fall', value: 'fall', label: 'Fall', months: ['september', 'october', 'november'] },
            { id: 'winter', value: 'winter', label: 'Winter', months: ['december', 'january', 'february'] },
          ],
        },
        {
          name: 'intakeYear',
          label: 'Intake Year',
          type: 'string',
          inputType: 'dropdown',
          required: true,
          optionsDynamic: true,
          optionsSource: 'years-from-current',
          options: [
            { value: '2025', label: '2025' },
            { value: '2026', label: '2026' },
            { value: '2027', label: '2027' },
            { value: '2028', label: '2028' },
          ],
        },
        {
          name: 'studyDuration',
          label: 'Choose your study duration',
          type: 'string',
          inputType: 'single-select-chips',
          required: true,
          options: [
            { id: 'ug-3', value: 'ug-3', label: 'Undergraduation 3 Years' },
            { id: 'ug-4', value: 'ug-4', label: 'Undergraduation 4 Years' },
            { id: 'ug-4plus', value: 'ug-4plus', label: 'Undergraduation 4+ Years' },
            { id: 'diploma', value: 'diploma', label: 'Diploma' },
            { id: 'pg-1', value: 'pg-1', label: 'Post Graduation 1 Year' },
            { id: 'pg-2', value: 'pg-2', label: 'Post Graduation 2 Years' },
          ],
        },
      ],
      nextButtonEnabledWhen: 'intake, intakeYear, and studyDuration are truthy (canProceed)',
    },
    {
      index: 4,
      stepId: 'study-industry',
      route: '/industry',
      stepLabel: 'Industry',
      component: 'StudyIndustrySelection',
      title: 'Choose Your Study Industry',
      subtitle: 'Discover your subject and experience your passion',
      inputType: 'single-select-grid-with-icons',
      required: true,
      autoAdvance: true,
      hasSearch: true,
      searchPlaceholder: 'Search',
      storeWrites: ['industry (setIndustry)'],
      field: { name: 'industry', type: 'string' },
      options: [
        { id: 'agriculture-forestry', value: 'agriculture-forestry', label: 'Agriculture & Forestry', iconUrl: '/assets/icons/industry/agriculture.svg' },
        { id: 'applied-sciences', value: 'applied-sciences-professions', label: 'Applied Sciences & Professions', iconUrl: '/assets/icons/industry/applied-sciences.svg' },
        { id: 'arts-design', value: 'arts-design-architecture', label: 'Arts, Design & Architecture', iconUrl: '/assets/icons/industry/arts.svg' },
        { id: 'business', value: 'business-management', label: 'Business & Management', iconUrl: '/assets/icons/industry/business.svg' },
        { id: 'computer', value: 'computer-science-it', label: 'Computer Science & IT', iconUrl: '/assets/icons/industry/computer.svg' },
        { id: 'education', value: 'education-training', label: 'Education & Training', iconUrl: '/assets/icons/industry/education.svg' },
        { id: 'engineering', value: 'engineering-technology', label: 'Engineering & Technology', iconUrl: '/assets/icons/industry/engineering.svg' },
        { id: 'environmental', value: 'environmental-studies-earth-sciences', label: 'Environmental Studies & Earth Sciences', iconUrl: '/assets/icons/industry/environmental.svg' },
        { id: 'hospitality', value: 'hospitality-leisure-sports', label: 'Hospitality, Leisure & Sports', iconUrl: '/assets/icons/industry/hospitality.svg' },
        { id: 'humanities', value: 'humanities', label: 'Humanities', iconUrl: '/assets/icons/industry/humanities.svg' },
        { id: 'journalism', value: 'journalism-media', label: 'Journalism & Media', iconUrl: '/assets/icons/industry/journalism.svg' },
        { id: 'law', value: 'law', label: 'Law', iconUrl: '/assets/icons/industry/law.svg' },
        { id: 'health', value: 'medicine-health', label: 'Medicine & Health', iconUrl: '/assets/icons/industry/health.svg' },
        { id: 'natural-sciences', value: 'natural-sciences-mathematics', label: 'Natural Sciences & Mathematics', iconUrl: '/assets/icons/industry/natural-sciences.svg' },
        { id: 'social', value: 'social-sciences', label: 'Social Sciences', iconUrl: '/assets/icons/industry/social.svg' },
      ],
      nextButtonEnabledWhen: 'industry is truthy (canProceed)',
    },
    {
      index: 5,
      stepId: 'study-area',
      route: '/study-area',
      stepLabel: 'Study Area',
      component: 'StudyAreaList',
      title: 'Choose Your Study Area',
      inputType: 'single-select-list',
      required: true,
      autoAdvance: true,
      hasSearch: true,
      searchPlaceholder: 'Search',
      dependsOn: 'industry',
      storeWrites: ['studyArea (setStudyArea)'],
      field: { name: 'studyArea', type: 'string' },
      conditionalOptions: {
        'computer-science-it': [
          { id: 'animation', value: 'animation', label: 'Animation' },
          { id: 'ai', value: 'artificial-intelligence', label: 'Artificial Intelligence' },
          { id: 'business-info', value: 'business-information-systems', label: 'Business Information Systems' },
          { id: 'computer-science', value: 'computer-sciences', label: 'Computer Sciences' },
          { id: 'cyber-security', value: 'cyber-security', label: 'Cyber Security' },
          { id: 'data-analytics', value: 'data-analytics', label: 'Data Analytics' },
          { id: 'data-science', value: 'data-science', label: 'Data Science' },
          { id: 'software', value: 'software-engineering', label: 'Software Engineering' },
        ],
        'business-management': [
          { id: 'accounting', value: 'accounting-finance', label: 'Accounting & Finance' },
          { id: 'marketing', value: 'marketing', label: 'Marketing' },
          { id: 'hr', value: 'human-resources', label: 'Human Resources' },
          { id: 'operations', value: 'operations-management', label: 'Operations Management' },
          { id: 'finance', value: 'finance', label: 'Finance' },
          { id: 'economics', value: 'economics', label: 'Economics' },
        ],
        'engineering-technology': [
          { id: 'mechanical', value: 'mechanical-engineering', label: 'Mechanical Engineering' },
          { id: 'electrical', value: 'electrical-engineering', label: 'Electrical Engineering' },
          { id: 'civil', value: 'civil-engineering', label: 'Civil Engineering' },
        ],
        'medicine-health': [
          { id: 'medicine', value: 'medicine', label: 'Medicine' },
          { id: 'nursing', value: 'nursing', label: 'Nursing' },
          { id: 'pharmacy', value: 'pharmacy', label: 'Pharmacy' },
          { id: 'psychology', value: 'psychology', label: 'Psychology' },
        ],
      },
      note: 'Options are dynamically loaded based on selected industry',
      nextButtonEnabledWhen: 'studyArea is truthy (canProceed)',
    },
    {
      index: 6,
      stepId: 'study-format',
      route: '/format',
      stepLabel: 'Format',
      component: 'StudyFormatSelection',
      title: 'Help us to understand better',
      required: true,
      autoAdvance: false,
      storeWrites: ['studyFormat (setStudyFormat) as a JSON-stringified object of selections'],
      sections: [
        {
          sectionId: 'study-format',
          title: 'Choose Your Study Format',
          inputType: 'single-select-buttons',
          storedUnderKey: 'format',
          field: { name: 'studyFormat.format', type: 'string' },
          options: [
            { id: 'full-time', value: 'full-time', label: 'Full Time', description: 'Traditional on-campus study', default: true },
            { id: 'part-time', value: 'part-time', label: 'Part Time', description: 'Flexible schedule for working professionals' },
          ],
        },
        {
          sectionId: 'attendance-type',
          title: 'Choose Your Study Attendance Type',
          inputType: 'single-select-buttons',
          storedUnderKey: 'attendance',
          field: { name: 'studyFormat.attendance', type: 'string' },
          options: [
            { id: 'on-campus', value: 'on-campus', label: 'On Campus', default: true },
            { id: 'online', value: 'online-learning', label: 'Online Learning' },
            { id: 'blended', value: 'blended-learning', label: 'Blended Learning' },
            { id: 'executive', value: 'executive-programs', label: 'Executive Programs' },
            { id: 'joint', value: 'joint-programs', label: 'Joint Programs' },
          ],
        },
        {
          sectionId: 'study-budget',
          title: 'Choose Your Desired Study Budget',
          inputType: 'single-select-buttons',
          storedUnderKey: 'budget',
          field: { name: 'studyFormat.budget', type: 'string' },
          options: [
            { id: '15-20k', value: '15000-20000', label: '£ 15,000 - £ 20,000', default: true },
            { id: '20-25k', value: '20000-25000', label: '£ 20,000 - £ 25,000' },
            { id: '25k+', value: '25000+', label: '£ 25,000+' },
            { id: '30k+', value: '30000+', label: '£ 30,000++' },
          ],
        },
        {
          sectionId: 'work-experience',
          title: 'Choose Your Applicable Work Experience',
          inputType: 'single-select-buttons',
          storedUnderKey: 'experience',
          field: { name: 'studyFormat.experience', type: 'string' },
          options: [
            { id: '0', value: '0-years', label: '0 Year' },
            { id: 'lt3', value: 'less-than-3-years', label: 'Less than 3 Years', default: true },
            { id: 'lt5', value: 'less-than-5-years', label: 'Less than 5 Years' },
            { id: '5+', value: '5-plus-years', label: '5+ Years' },
          ],
        },
      ],
      nextButtonEnabledWhen: 'studyFormat string is truthy (canProceed)',
    },
    {
      index: 7,
      stepId: 'academics',
      route: '/academics',
      stepLabel: 'Academics',
      component: 'RecentAcademicsInfo',
      title: 'Help us with your previous Academics for better Suitability',
      required: true,
      autoAdvance: false,
      storeWrites: [
        'academics.secondary (year, grade, medium)',
        'academics.higherSecondary (year, grade, medium)',
        'academics.undergrad (optional object when expanded)',
        'academics.postgrad (optional object when expanded)',
      ],
      mediumOptions: [
        { value: 'english', label: 'English' },
        { value: 'hindi', label: 'Hindi' },
        { value: 'regional', label: 'Regional' },
      ],
      sections: [
        {
          sectionId: 'secondary-school',
          title: 'Secondary school Certificate / 10th',
          collapsible: false,
          required: true,
          fields: [
            {
              name: 'academics.secondary.year',
              label: 'Enter Year of completion',
              placeholder: 'Enter Year of Completion',
              type: 'number',
              inputType: 'text',
              required: true,
              validation: { min: 1950, max: 2030 },
            },
            {
              name: 'academics.secondary.grade',
              label: 'Enter the Achieved Grade',
              placeholder: 'Enter the Achieved Grade',
              type: 'string',
              inputType: 'text',
              required: true,
            },
            {
              name: 'academics.secondary.medium',
              label: 'Medium',
              type: 'string',
              inputType: 'dropdown',
              required: false,
              options: [
                { value: 'english', label: 'English' },
                { value: 'hindi', label: 'Hindi' },
                { value: 'regional', label: 'Regional' },
              ],
            },
          ],
        },
        {
          sectionId: 'higher-secondary',
          title: 'Higher Secondary school Certificate / 12th',
          collapsible: false,
          required: true,
          fields: [
            {
              name: 'academics.higherSecondary.year',
              label: 'Enter Year of completion',
              placeholder: 'Enter Year of Completion',
              type: 'number',
              inputType: 'text',
              required: true,
              validation: { min: 1950, max: 2030 },
            },
            {
              name: 'academics.higherSecondary.grade',
              label: 'Enter the Achieved Grade',
              placeholder: 'Enter the Achieved Grade',
              type: 'string',
              inputType: 'text',
              required: true,
            },
            {
              name: 'academics.higherSecondary.medium',
              label: 'Medium',
              type: 'string',
              inputType: 'dropdown',
              required: false,
              options: [
                { value: 'english', label: 'English' },
                { value: 'hindi', label: 'Hindi' },
                { value: 'regional', label: 'Regional' },
              ],
            },
          ],
        },
        {
          sectionId: 'under-graduation',
          title: 'Under Graduation',
          collapsible: true,
          expandable: true,
          expandIcon: 'chevron-down',
          required: false,
          fields: [
            {
              name: 'academics.undergrad.degreeType',
              label: 'Choose the Type of Degree',
              placeholder: 'Choose the Type of Degree',
              type: 'string',
              inputType: 'dropdown',
              required: false,
              options: [
                { value: 'be-btech', label: 'BE/B.Tech- Bachelor of Technology' },
                { value: 'barch', label: 'B.Arch- Bachelor of Architecture' },
                { value: 'bba', label: 'BBA - Bachelor of Business Administration' },
                { value: 'bcom', label: 'BCom - Bachelor of Commerce' },
                { value: 'bca', label: 'BCA- Bachelor of Computer Applications' },
                { value: 'bsc-it', label: 'B.Sc.- Information Technology' },
                { value: 'bpharma', label: 'BPharma- Bachelor of Pharmacy' },
                { value: 'bsc-interior', label: 'B.Sc- Interior Design' },
                { value: 'bds', label: 'BDS- Bachelor of Dental Surgery' },
                { value: 'bsc-maths', label: 'B.Sc. Mathematics' },
                { value: 'bsc-chemistry', label: 'B.Sc. Chemistry' },
                { value: 'others', label: 'Others' },
              ],
            },
            {
              name: 'academics.undergrad.medium',
              label: 'Medium',
              type: 'string',
              inputType: 'dropdown',
              required: false,
              options: [
                { value: 'english', label: 'English' },
                { value: 'hindi', label: 'Hindi' },
                { value: 'regional', label: 'Regional' },
              ],
            },
            {
              name: 'academics.undergrad.startYear',
              label: 'Start Year',
              placeholder: 'Enter the Start Year',
              type: 'number',
              inputType: 'text',
              required: false,
            },
            {
              name: 'academics.undergrad.endYear',
              label: 'End Year',
              placeholder: 'Enter the End Year',
              type: 'number',
              inputType: 'text',
              required: false,
            },
            {
              name: 'academics.undergrad.grade',
              label: 'Enter Achieved Grade',
              placeholder: 'Enter the Achieved Grade',
              type: 'string',
              inputType: 'text',
              required: false,
            },
            {
              name: 'academics.undergrad.backlogs',
              label: 'Enter total Backlogs',
              placeholder: 'Enter Total Backlogs',
              type: 'number',
              inputType: 'number',
              required: false,
            },
          ],
        },
        {
          sectionId: 'post-graduation',
          title: 'Post Graduation',
          collapsible: true,
          expandable: true,
          expandIcon: 'chevron-down',
          required: false,
          fields: [
            {
              name: 'academics.postgrad.degreeType',
              label: 'Choose the Type of Degree',
              placeholder: 'Choose the Type of Degree',
              type: 'string',
              inputType: 'dropdown',
              required: false,
              options: [
                { value: 'mtech', label: 'M.Tech' },
                { value: 'mba', label: 'MBA' },
                { value: 'mca', label: 'MCA' },
                { value: 'ms', label: 'MS' },
                { value: 'brs', label: 'BRS' },
                { value: 'others', label: 'Others' },
              ],
            },
            {
              name: 'academics.postgrad.medium',
              label: 'Medium',
              type: 'string',
              inputType: 'dropdown',
              required: false,
              options: [
                { value: 'english', label: 'English' },
                { value: 'hindi', label: 'Hindi' },
                { value: 'regional', label: 'Regional' },
              ],
            },
            {
              name: 'academics.postgrad.startYear',
              label: 'Start Year',
              placeholder: 'Enter the Start Year',
              type: 'number',
              inputType: 'text',
              required: false,
            },
            {
              name: 'academics.postgrad.endYear',
              label: 'End Year',
              placeholder: 'Enter the End Year',
              type: 'number',
              inputType: 'text',
              required: false,
            },
            {
              name: 'academics.postgrad.grade',
              label: 'Enter Achieved Grade',
              placeholder: 'Enter the Achieved Grade',
              type: 'string',
              inputType: 'text',
              required: false,
            },
            {
              name: 'academics.postgrad.backlogs',
              label: 'Enter total Backlogs',
              placeholder: 'Enter Total Backlogs',
              type: 'number',
              inputType: 'number',
              required: false,
            },
          ],
        },
      ],
      nextButtonEnabledWhen:
        'secondary.year + secondary.grade + higherSecondary.year + higherSecondary.grade are truthy (canProceed)',
    },
    {
      index: 8,
      stepId: 'test-preferences',
      route: '/assessment',
      stepLabel: 'Assessment',
      component: 'TestPreferences',
      title:
        'Help us with your Additional Assessment that might be helpful for mapping your Requirements on the best school for your chosen destination',
      required: false,
      autoAdvance: false,
      sections: [
        {
          sectionId: 'adaptive-test',
          title: 'Choose Adaptive Test',
          inputType: 'dropdown',
          field: { name: 'adaptiveTest', type: 'string' },
          options: [
            { id: 'psat', value: 'psat', label: 'Per SAT - Pre Scholastic Assessment Test' },
            { id: 'sat', value: 'sat', label: 'SAT - Scholastic Assessment Test' },
            { id: 'act', value: 'act', label: 'ACT - American College Test' },
            { id: 'gre', value: 'gre', label: 'GRE - Graduate Record Examinations' },
            { id: 'gmat', value: 'gmat', label: 'GMAT - Graduate Management Admission Test' },
            { id: 'consider-later', value: 'consider-later', label: 'I wish to consider the tests but later!' },
            { id: 'not-consider', value: 'not-consider', label: 'I do not wish to consider the test for making applications**!' },
          ],
        },
        {
          sectionId: 'english-language-test',
          title: 'Choose English Language Test',
          inputType: 'dropdown',
          field: { name: 'englishLanguageTest', type: 'string' },
          options: [
            { id: 'ielts', value: 'ielts', label: 'IELTS - International English Language Testing Systems' },
            { id: 'toefl', value: 'toefl', label: 'TOEFL - Test of English as a Foreign Language' },
            { id: 'pte', value: 'pte', label: 'PTE - Pearson Test of English' },
            { id: 'det', value: 'det', label: 'DET - Duolingo English Test' },
            { id: 'consider-later', value: 'consider-later', label: 'I wish to consider the tests but later!' },
            { id: 'not-consider', value: 'not-consider', label: 'I do not wish to consider the test for making applications**!' },
          ],
        },
      ],
    },
    {
      index: 9,
      stepId: 'contact-info',
      route: '/contact',
      stepLabel: 'Contact',
      component: 'ContactInfo',
      title: 'Almost there...',
      subtitle:
        'We enable you to explore all the study options in one place and to find the best study programme that matches your needs, goals, and preferences.',
      required: true,
      autoAdvance: false,
      submitAction: 'submitApplication',
      storeWrites: [
        'contact (firstName, lastName, phone, email, emailConsent, termsConsent)',
        'submission state (isSubmitting, isSubmitted, error)',
      ],
      fields: [
        {
          name: 'contact.firstName',
          label: 'First Name',
          placeholder: 'First Name',
          type: 'string',
          inputType: 'text',
          required: true,
          validation: { minLength: 1, maxLength: 100 },
        },
        {
          name: 'contact.lastName',
          label: 'Last Name',
          placeholder: 'Last Name',
          type: 'string',
          inputType: 'text',
          required: true,
          validation: { minLength: 1, maxLength: 100 },
        },
        {
          name: 'contact.phone',
          label: 'Phone Number',
          placeholder: 'Phone Number',
          type: 'string',
          inputType: 'tel',
          required: true,
        },
        {
          name: 'contact.email',
          label: 'Email',
          placeholder: 'Email ID',
          type: 'string',
          inputType: 'email',
          required: true,
          validation: { format: 'email' },
        },
        {
          name: 'contact.emailConsent',
          label:
            'Receive monthly emails right to your inbox with programmes that match your individual profile as well as useful information to plan your study abroad journey.',
          type: 'boolean',
          inputType: 'checkbox',
          required: false,
          defaultValue: true,
        },
        {
          name: 'contact.termsConsent',
          label: 'By registering, you agree to our Privacy Statement and Terms and Conditions.',
          type: 'boolean',
          inputType: 'checkbox',
          required: true,
          defaultValue: true,
        },
      ],
      submitButton: {
        labelIdle: 'Submit',
        labelSubmitting: 'Submitting...',
        style: 'primary',
        color: '#A51C30',
      },
      clientSideErrorStrings: [
        'Please accept the terms and conditions',
        'Please fill in all required fields',
        'Submission failed. Please try again.',
        'An error occurred. Please try again.',
      ],
      onSuccess: 'submitApplication(getApplicationData()) then goToNext() to /thank-you',
    },
    {
      index: 10,
      stepId: 'thank-you',
      route: '/thank-you',
      stepLabel: 'Complete',
      component: 'ThankYou',
      title: 'Thankyou..!',
      isTerminal: true,
      storeWrites: ['resetForm() on goHome click'],
      pageMetadata: {
        bodyLinesGroup1: [
          'Thank you for letting us know your interest',
          'and your study abroad partner will connect',
          'you at the earliest possible.',
        ],
        bodyLinesGroup2: ['We are FULLY DIGITAL and focusing', 'for truest global student recruitment.'],
      },
      actions: [{ name: 'goHome', label: 'Home', icon: 'HomeIcon inline svg', action: 'resetForm(); goHome();' }],
    },
  ],
  apiConfig: {
    baseUrlDefault: 'https://api.admitsconnect.com',
    envVar: 'import.meta.env.VITE_API_BASE_URL',
    endpoints: {
      countries: '/api/countries',
      studyLevels: '/api/study-levels',
      degreeTypes: '/api/degree-types',
      industries: '/api/industries',
      studyAreas: '/api/study-areas',
      studyFormats: '/api/study-formats',
      intakes: '/api/intakes',
      studyDurations: '/api/study-durations',
      tags: '/api/tags',
      applications: '/api/applications',
    },
    submitApplicationHardcoded: {
      rejectIf: 'missing contact.email OR missing contact.termsConsent',
      rejectMessage: 'Please complete all required fields and accept terms.',
      successMessage:
        'Your application has been submitted successfully! Our team will contact you soon.',
    },
  },
  globalConfig: {
    disclaimer:
      "*This information is for reference only, we do not endorse any specific Universities or Courses. This information is provided solely for educational reference and we'd love to help you.",
    headerStats: { courses: '3,43,000+', destinations: '9' },
  },
  iconMappings: {
    industries: {
      'agriculture-forestry': { iconUrl: '/assets/icons/industry/agriculture.svg', iconClass: 'industry-agriculture' },
      'applied-sciences-professions': { iconUrl: '/assets/icons/industry/applied-sciences.svg', iconClass: 'industry-applied-sciences' },
      'arts-design-architecture': { iconUrl: '/assets/icons/industry/arts.svg', iconClass: 'industry-arts' },
      'business-management': { iconUrl: '/assets/icons/industry/business.svg', iconClass: 'industry-business' },
      'computer-science-it': { iconUrl: '/assets/icons/industry/computer.svg', iconClass: 'industry-computer' },
      'education-training': { iconUrl: '/assets/icons/industry/education.svg', iconClass: 'industry-education' },
      'engineering-technology': { iconUrl: '/assets/icons/industry/engineering.svg', iconClass: 'industry-engineering' },
      'environmental-studies-earth-sciences': { iconUrl: '/assets/icons/industry/environmental.svg', iconClass: 'industry-environmental' },
      'hospitality-leisure-sports': { iconUrl: '/assets/icons/industry/hospitality.svg', iconClass: 'industry-hospitality' },
      humanities: { iconUrl: '/assets/icons/industry/humanities.svg', iconClass: 'industry-humanities' },
      'journalism-media': { iconUrl: '/assets/icons/industry/journalism.svg', iconClass: 'industry-journalism' },
      law: { iconUrl: '/assets/icons/industry/law.svg', iconClass: 'industry-law' },
      'medicine-health': { iconUrl: '/assets/icons/industry/health.svg', iconClass: 'industry-health' },
      'natural-sciences-mathematics': { iconUrl: '/assets/icons/industry/natural-sciences.svg', iconClass: 'industry-natural-sciences' },
      'social-sciences': { iconUrl: '/assets/icons/industry/social.svg', iconClass: 'industry-social' },
    },
    flags: {
      australia: '/assets/icons/flags/Australia.svg',
      canada: '/assets/icons/flags/Canada.svg',
      uk: '/assets/icons/flags/UK.svg',
      usa: '/assets/icons/flags/USA.svg',
      ireland: '/assets/icons/flags/Ireland.svg',
      germany: '/assets/icons/flags/Germany.svg',
      switzerland: '/assets/icons/flags/Switzerland.svg',
      sweden: '/assets/icons/flags/Sweden.svg',
      netherlands: '/assets/icons/flags/Netherlands.svg',
      'new-zealand': '/assets/icons/flags/NewZealand.svg',
      cyprus: '/assets/icons/flags/Cyprus.svg',
      denmark: '/assets/icons/flags/Denmark.svg',
      france: '/assets/icons/flags/France.svg',
      italy: '/assets/icons/flags/Italy.svg',
      finland: '/assets/icons/flags/Finland.svg',
      latvia: '/assets/icons/flags/Latvia.svg',
      malta: '/assets/icons/flags/Malta.svg',
      norway: '/assets/icons/flags/Norway.svg',
      poland: '/assets/icons/flags/Poland.svg',
      singapore: '/assets/icons/flags/Singapore.svg',
      spain: '/assets/icons/flags/Spain.svg',
    },
    stats: {
      'students-helped': '/assets/icons/stats/Students Helped icon.svg',
      'study-options': '/assets/icons/stats/Study Options Icon.svg',
      'global-universities': '/assets/icons/stats/Global Universities icon.svg',
      'transparent-process': '/assets/icons/stats/Transparent Process icon.svg',
      'global-events': '/assets/icons/stats/Global Events icon.svg',
      'virtual-sessions': '/assets/icons/stats/Virtual sessions icon.svg',
      'student-satisfaction': '/assets/icons/stats/Student satisfaction icon.svg',
      'study-destinations': '/assets/icons/stats/Study destination Icon.svg',
      'years-experience': '/assets/icons/stats/Years Experience icon.svg',
    },
  },
} as const;

export type ApplyUniNowCourseExplorerSource = typeof applyUniNowCourseExplorerSource;


